# Generated by Django 4.2.4 on 2023-10-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0005_menu'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('item', 'restaurant')},
        ),
    ]
