# Generated by Django 4.2.4 on 2023-10-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0010_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
