# Generated by Django 4.2.4 on 2023-10-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0017_orderdetail_created_at_orderdetail_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantRating',
        ),
    ]
