# Generated by Django 4.2.4 on 2023-11-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0019_restaurantrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(null=True, upload_to='pics/menuitems'),
        ),
    ]
