# Generated by Django 4.2.4 on 2023-10-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='gender_types',
            new_name='gender',
        ),
    ]
